####### --- OGN receiver configuration --- #############################################################
#
#      This is the master configuration for the OGN software. This file must be valid Bash to be sourced
#      by OGN-receiver-config-manager. The receiver is reconfigured on each boot.
#
#      All variables in the Mandatory section MUST be entered or the receiver will not start
#      Optional values are, well, optional
#
########################################################################################################

### --- Mandatory configuration

# Please follow naming convention (http://wiki.glidernet.org/receiver-naming-convention) when entering ReceiverName
# development defaults

ReceiverName="CharlyG2"
Latitude="46.8917"
Longitude="10.5011"

piUserPassword="KarlBaldauf1"

### --- Optional configuration

# - Wifi configuration
# wifiName="Wlan_Charly"
# wifiPassword="66karl66"
# wifiCountry="AT"

# - Bias Tee for rtlsdr.com's receiver 
BiasTee="0"

# - Remote administration settings
RemoteAdminEnabled="YES"

# the name of the remote admin user is replaced by install.sh, so change it there, not here
RemoteAdminUser=REMOTEADMINUSER

# - receiver settings
# FreqCorr="+42" # is detected automatically
# Altitude="1357"
# GSMCenterFreq="950"
# GSMGain="30"
# SampleRate=2.0
# OGNCenterFreq=868.8
# OGNgain=50
# EnableCoreOGNTeamRemoteAdmin="true" # this variable is not implemented, remote access is provided by remotelysecu.re


